<a href="https://colab.research.google.com/github/helinatefera/10xWeek6/blob/task-2/notebooks/task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('/content/data.csv')

In [4]:
data.head()

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2018-11-15T02:18:49Z,2,0
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2018-11-15T02:19:08Z,2,0
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,UGX,256,ProviderId_6,ProductId_1,airtime,ChannelId_3,500.0,500,2018-11-15T02:44:21Z,2,0
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,UGX,256,ProviderId_1,ProductId_21,utility_bill,ChannelId_3,20000.0,21800,2018-11-15T03:32:55Z,2,0
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-644.0,644,2018-11-15T03:34:21Z,2,0

In [5]:
len(data)

95662

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95662 entries, 0 to 95661
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   TransactionId         95662 non-null  object
 1   BatchId               95662 non-null  object
 2   AccountId             95662 non-null  object
 3   SubscriptionId        95662 non-null  object
 4   CustomerId            95662 non-null  object
 5   CurrencyCode          95662 non-null  object
 6   CountryCode           95662 non-null  int64
 7   ProviderId            95662 non-null  object
 8   ProductId             95662 non-null  object
 9   ProductCategory       95662 non-null  object
 10  ChannelId             95662 non-null  object
 11  Amount                95662 non-null  float64
 12  Value                 95662 non-null  int64
 13  TransactionStartTime  95662 non-null  object
 14  PricingStrategy       95662 non-null  int64
 15  FraudResult           95662 non-null  int64
dtypes: float64(1), int64(4), object(11)
memory usage: 11.7+ MB

In [7]:
data.describe()

       CountryCode        Amount         Value  PricingStrategy   FraudResult
count      95662.0  9.566200e+04  9.566200e+04     95662.000000  95662.000000
mean         256.0  6.717846e+03  9.900584e+03         2.255974      0.002018
std            0.0  1.233068e+05  1.231221e+05         0.732924      0.044872
min          256.0 -1.000000e+06  2.000000e+00         0.000000      0.000000
25%          256.0 -5.000000e+01  2.750000e+02         2.000000      0.000000
50%          256.0  1.000000e+03  1.000000e+03         2.000000      0.000000
75%          256.0  2.800000e+03  5.000000e+03         2.000000      0.000000
max          256.0  9.880000e+06  9.880000e+06         4.000000      1.000000

from matplotlib import pyplot as plt
_df_0['CountryCode'].plot(kind='hist', bins=20, title='CountryCode')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Amount'].plot(kind='hist', bins=20, title='Amount')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Value'].plot(kind='hist', bins=20, title='Value')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['PricingStrategy'].plot(kind='hist', bins=20, title='PricingStrategy')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='CountryCode', y='Amount', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='Amount', y='Value', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='Value', y='PricingStrategy', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='PricingStrategy', y='FraudResult', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8['CountryCode'].plot(kind='line', figsize=(8, 4), title='CountryCode')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9['Amount'].plot(kind='line', figsize=(8, 4), title='Amount')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['Value'].plot(kind='line', figsize=(8, 4), title='Value')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_11['PricingStrategy'].plot(kind='line', figsize=(8, 4), title='PricingStrategy')
plt.gca().spines[['top', 'right']].set_visible(False)

In [8]:
data['TransactionStartTime'] = pd.to_datetime(data['TransactionStartTime'])
numerical_columns = ["Amount", "Value", "CountryCode", "PricingStrategy", "FraudResult"]
numerical_summary = data[numerical_columns].describe()

numerical_summary.loc["range"] = numerical_summary.loc["max"] - numerical_summary.loc["min"]
numerical_summary.loc["skew"] = data[numerical_columns].skew()
numerical_summary.loc["kurtosis"] = data[numerical_columns].kurt()

categorical_columns = ["CurrencyCode", "ProviderId", "ProductId", "ProductCategory", "ChannelId"]
categorical_summary = {}
for col in categorical_columns:
    categorical_summary[col] = data[col].value_counts()

print("Numerical Summary Statistics:\n", numerical_summary)
print("\nCategorical Summary Statistics:")
for col, counts in categorical_summary.items():
    print(f"{col}:\n{counts}\n")

Numerical Summary Statistics:
                 Amount         Value  CountryCode  PricingStrategy  \
count     9.566200e+04  9.566200e+04      95662.0     95662.000000
mean      6.717846e+03  9.900584e+03        256.0         2.255974
std       1.233068e+05  1.231221e+05          0.0         0.732924
min      -1.000000e+06  2.000000e+00        256.0         0.000000
25%      -5.000000e+01  2.750000e+02        256.0         2.000000
50%       1.000000e+03  1.000000e+03        256.0         2.000000
75%       2.800000e+03  5.000000e+03        256.0         2.000000
max       9.880000e+06  9.880000e+06        256.0         4.000000
range     1.088000e+07  9.879998e+06          0.0         4.000000
skew      5.109849e+01  5.129109e+01          0.0         1.659057
kurtosis  3.363128e+03  3.378069e+03          0.0         2.087534

           FraudResult
count     95662.000000
mean          0.002018
std           0.044872
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
range         1.000000
skew         22.196295
kurtosis    490.685762

Categorical Summary Statistics:
CurrencyCode:
CurrencyCode
UGX    95662
Name: count, dtype: int64

ProviderId:
ProviderId
ProviderId_4    38189
ProviderId_6    34186
ProviderId_5    14542
ProviderId_1     5643
ProviderId_3     3084
ProviderId_2       18
Name: count, dtype: int64

ProductId:
ProductId
ProductId_6     32635
ProductId_3     24344
ProductId_10    15384
ProductId_15    11964
ProductId_1      2885
ProductId_4      2403
ProductId_21     1512
ProductId_11     1377
ProductId_19      965
ProductId_14      789
ProductId_13      296
ProductId_2       236
ProductId_20      216
ProductId_8       197
ProductId_24      175
ProductId_22      112
ProductId_7        86
ProductId_27       31
ProductId_5        25
ProductId_9        17
ProductId_16       10
ProductId_12        2
ProductId_23        1
Name: count, dtype: int64

ProductCategory:
ProductCategory
financial_services    45405
airtime               45027
utility_bill           1920
data_bundles           1613
tv                     1279
ticket                  216
movies                  175
transport                25
other                     2
Name: count, dtype: int64

ChannelId:
ChannelId
ChannelId_3    56935
ChannelId_2    37141
ChannelId_5     1048
ChannelId_1      538
Name: count, dtype: int64